name: CI tests

on:
  pull_request:
  push:
    branches:
    - Live

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
        cache-dependency-path: |
          requirements*.txt


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt -r requirements-test.txt
        pip install .

    - name: Run tests
      run: pytest -rs -vvv
